language: c

services:
  - docker

jobs:
  include:
    - stage: autotools
      script:
        docker build -t autotools -f autotools.Dockerfile .
    - stage: cmake
      script:
        docker build -t cmake -f cmake.Dockerfile .
    - stage: meson
      script:
        docker build -t meson -f meson.Dockerfile .
