#!/bin/bash

miracle-stop-network-manager

. miracle-utils.sh

echo starting wpa_supplicant for normal connection
start_network_manager

exit 0

# ---
# Nothing of the code below is needed to restart wireless anymore on systemd, tweak it for distros based 
# on service or other system admin daemon.

ETHER_NAMES=$(find_choosable_networknames)

ETHER_COUNT=$(echo "$ETHER_NAMES" | wc -l)

if [ 0 = $ETHER_COUNT ]
then
   echo There is no net devices avaliable
   exit 1
elif [ 1 = $ETHER_COUNT ]
then
   ETHERNAME="$ETHER_NAMES"
elif [ 2 -le $ETHER_COUNT ]
then
   echo choose device for normal connection:
   QUIT="exit"
   select et_name in $ETHER_NAMES $QUIT
   do
      case $et_name
      in
      "$QUIT")
          exit
          ;;
      "")
          if [ "$REPLY" = $QUIT ]
          then
              exit
          else
              echo unknow $REPLY
          fi
          ;;
      *)
          ETHERNAME=$et_name
          break
          ;;
        esac
   done
fi

# default path for config file
CONFIG_FILE=${1:-/run/network/wpa_supplicant_${ETHERNAME}.conf}

sudo wpa_supplicant -B -u -P /run/wpa_supplicant_${ETHERNAME}pid -i ${ETHERNAME} -D nl80211 -c$CONFIG_FILE

