/* Generated by vala-dbus-binding-tool 0.4.0. Do not modify! */
/* Generated with: /usr/bin/vala-dbus-binding-tool --gdbus --no-synced --rename-namespace=org:Org --rename-namespace=freedesktop:Freedesktop --rename-namespace=miracle:Miracle --rename-namespace=wifi:Wifi --rename-namespace=wfd:Wfd --api-path=/home/derekdai/Projects/miraclecast/demo/dbus */
using GLib;

namespace Org {

	namespace Freedesktop {

		namespace Miracle {

			namespace Wifi {

				[DBus (name = "org.freedesktop.miracle.wifi.Peer", timeout = 120000)]
				public interface Peer : GLib.Object {

					[DBus (name = "Connect")]
					public abstract async void connect(string param0, string param1) throws DBusError, IOError;

					[DBus (name = "Disconnect")]
					public abstract async void disconnect() throws DBusError, IOError;

					[DBus (name = "Link")]
					public abstract GLib.ObjectPath link { owned get; }

					[DBus (name = "P2PMac")]
					public abstract string p2_p_mac { owned get; }

					[DBus (name = "FriendlyName")]
					public abstract string friendly_name { owned get; }

					[DBus (name = "Connected")]
					public abstract bool connected {  get; }

					[DBus (name = "Interface")]
					public abstract string interface { owned get; }

					[DBus (name = "LocalAddress")]
					public abstract string local_address { owned get; }

					[DBus (name = "RemoteAddress")]
					public abstract string remote_address { owned get; }

					[DBus (name = "WfdSubelements")]
					public abstract string wfd_subelements { owned get; }

					[DBus (name = "ProvisionDiscovery")]
					public signal void provision_discovery(string param0, string param1);

					[DBus (name = "GoNegRequest")]
					public signal void go_neg_request(string param0, string param1);

					[DBus (name = "FormationFailure")]
					public signal void formation_failure(string param0);
				}

				[DBus (name = "org.freedesktop.miracle.wifi.Link", timeout = 120000)]
				public interface Link : GLib.Object {

					[DBus (name = "Manage")]
					public abstract async void manage() throws DBusError, IOError;

					[DBus (name = "Unmanage")]
					public abstract async void unmanage() throws DBusError, IOError;

					[DBus (name = "InterfaceIndex")]
					public abstract uint interface_index {  get; }

					[DBus (name = "MACAddress")]
					public abstract string m_a_c_address { owned get; }

					[DBus (name = "InterfaceName")]
					public abstract string interface_name { owned get; }

					[DBus (name = "FriendlyName")]
					public abstract string friendly_name { owned get; set; }

					[DBus (name = "Managed")]
					public abstract bool managed {  get; }

					[DBus (name = "P2PScanning")]
					public abstract bool p2_p_scanning {  get; set; }

					[DBus (name = "WfdSubelements")]
					public abstract string wfd_subelements { owned get; set; }
				}
			}
		}
	}
}
